### PR TITLE
Slim 638 decouple mbus device

### PR DESCRIPTION
**Pull request by hannek24**

### CODE REVIEW

**Comment by CLAAdmin** [comment]
[CLA assistant check](http://52.16.237.165:80/OSGP/Documentation?pullRequest=101) <br/>You should sign our Contributor License Agreement in order to get your pull request merged.<br/>

**Comment by robindenadel** [comment]
adapt summary.md as well

**Comment by hannek24** [comment]
For the reviewer: I repeatedly signed the "Contributor License Agreement". However this check remains open. So please ignore it (if you can :-) )

**Comment by hannek24** [comment]
The two added links in the SUMMARY.md file are not working when viewing (clicking) from within the branch. Pieter Zeeuw looked at this and confirmed that they are correct and that they should/will work when merged to development.

**Pull request merged**
