### PR TITLE
Restructure documentation

### PR DESCRIPTION
**Pull request by Sander3003**
I tried to improve the documentation structure to meet future needs and improvements. 
#25

### CODE REVIEW

**Comment by CLAAdmin** [comment]
[CLA assistant check](http://52.16.237.165:80/OSGP/Documentation?pullRequest=74) <br/>All committers of the pull request should sign our Contributor License Agreement in order to get your pull request merged.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Sander3003<br/>:x: web-flow

**Comment by Sander3003** [comment]
It is unclear to me who "web-flow" is. It might me an error on my side.

**Comment by kevinsmeets** [comment]
This is web-flow: https://github.com/web-flow

**Comment by Sander3003** [comment]
Oke, Thank you. I don't see an issue with the CLA check

**Comment by kevinsmeets** [comment]
These changes cause many links to not work.
See:
http://54.77.62.182/view/Pull%20Request%20Builder/job/OSGP_Documentation_pr/101/artifact/_book/index.html

When is this work finished?

**Comment by Sander3003** [comment]
I will fix them now

**Comment by Sander3003** [comment]
@kevinsmeets the errors are solved now. http://54.77.62.182/job/OSGP_Documentation_pr/lastSuccessfulBuild/artifact/_book/index.html

**Comment by Sander3003** [comment]
@kevinsmeets Do you agree with my changes in this pull-request?

**Comment by Jonasvdbo** [comment]
Additionally, I reviewed the suggested setup and I agree with this new setup. When all errors are solved, this pull-request can be confirmed.

**Pull request merged**
