### PR TITLE
Governance improvement suggestion chapter split up

### PR DESCRIPTION
**Pull request by Sander3003**
I'd like to get review comment form @phoutman @marcelvanhal @egmondha @kevinsmeets, Thorben  and others with interest. Let me know what you think. ## 4.3 Governance is the most important part.

### CODE REVIEW

**Comment by kevinsmeets** [comment]
The proposed changes look good to me. If one wants to check the resulting GitBook pages, use this link: http://54.77.62.182/job/OSGP_Documentation_pr/15/artifact/_book/chapter4/index.html

@Sander3003, the merge window will close on Monday Februari 29th. Do you want to incorperate these changes in release 3.1.0? I guess so :)
@frankheijnders, can you act upon this? Make sure people have enough time to comment on this pull request. However, when you get around to releasing this repository, either merge this pull request, or leave it out, depending om what Sander would like :+1: 

LGTM

**Comment by Sander3003** [comment]
Its for me more important that everybody agrees on this (e.g. community council and maintainers roles). It is fine for me we don't make the 3.1 release. Quality is more important than speed at this point.

**Comment by Sander3003** [comment]
@bvdzwet @rlemmers Do you guys agree on the maintainers role? See ## 4.3 Governance.

**Comment by WalterBorgstein** [comment]
I think the weight of the current council members as suggested it not appropiate. I would recommend having Hans van Egmond and/or Paul Houtman as a member. The set-up of the text is good!.

**Comment by egmondha** [comment]
Hi Sander,

Some (textual) suggestions for improvement:

With OSGP we intend to have the right balance between a benevolent Dictator and a Formal Meritocracy in order to have a balanced decision-making process and to prevent unwanted dictators and everlasting discussions. The basic principle is that decisions are based on consensus. If this decision making process takes too long or a decision is required, the community council has the authority to make a decision.
The following governance and rules should be respected:
Community council
The community council consists of 5 members and has the authority to make decisions on all community related subjects. 
The community council is responsible for:
•	General ambitions, objectives and goals 
•	Principles and understandings
•	Governance and consultation bodies
•	Guidelines and procedures and tool selection
•	Contribution (process) of individual members
•	Architectural and (development) infrastructural choices
•	Raise subjects/issues that are important for the direction/development of the community
When the community grows, members of the community council can be elected. If the situation demands or requires it, the community council has the ability to establish sub councils for a specific subject, area of domain. One member (seat) represents the OSGP Foundation (once started) for alignment between the objectives of the foundation and the direction of the development of the online community.
The community council consist of the following members:
•	Sander Jansen - Open source consultant – Chairman (https://github.com/Sander3003)
•	Paul Houtman – Lead Architect (https://github.com/paulhoutman) ??
•	Kevin Smeets -  Maintainer (https://github.com/kevinsmeets)
•	Thorben Meijer - Marketing expert
•	Vacancy - OSGP foundation seat
If you would like to join the community council, please contact us!
The (online) community council meetings will happen once a month.

**Comment by Sander3003** [comment]
Thanks for joining the discussion!

**Pull request merged**
