### PR TITLE
Small improvements in README.md and CONTRIBUTE.md

### PR DESCRIPTION
**Pull request by Sander3003**

### CODE REVIEW

**Comment by CLAAdmin** [comment]
[CLA assistant check](http://52.16.237.165:80/OSGP/Documentation?pullRequest=97) <br/>You should sign our Contributor License Agreement in order to get your pull request merged.<br/>

**Comment by pczeeuw** [comment]
@Sander3003 
Agreed with the changes.

You might want to check the CLA however.

**Comment by Sander3003** [comment]
@pczeeuw @bvdzwet I'm having trouble with signing the the CLA. I tried it several times. I'm not able to trace down the issue so far. I had problems with the CLA before: https://github.com/OSGP/Documentation/pull/82 . It looks like that github changed some things related to changes made via the github website (web-flow https://github.com/web-flow).  I will fire an Jira ticket on this topic.

**Comment by Sander3003** [comment]
(OC-157) An cla assistant update can solve the problem: https://github.com/cla-assistant/cla-assistant/issues/122 . It's an know issue

**Pull request closed without merging**
