### PR TITLE
Feature community management

### PR DESCRIPTION
**Pull request by EmmaKoster**
O dear, there seems to be a merge problem!

### CODE REVIEW

**Comment by CLAAdmin** [comment]
[CLA assistant check](http://52.16.237.165:3000/OSGP/Documentation?pullRequest=7) <br/>All committers of the pull request should sign our Contributor License Agreement in order to get your pull request merged.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: EmmaKoster<br/>:x: Sander3003

**Comment by EmmaKoster** [comment]
Will look at this tomorrow. It's a mess!

**Comment by Sander3003** [comment]
I signed :)

**Comment by kevinsmeets** [comment]
Cool :+1:

**Comment by kevinsmeets** [comment]
Hi Guys, I tried to help out with the merge conflict. It has been solved. I hope I made the right choice, otherwise you might have to change some of the text again.

**Comment by EmmaKoster** [comment]
Thanks Kevin for the help with the merge problem. I will have a look at the picture guidelines and change that in the development branch.

**Pull request merged**
