### PR TITLE
Update Code-of-conduct.md

### PR DESCRIPTION
**Pull request by Sander3003**
info (at) opensmartgridplatform.org is more company agnostic e-mail adress

### CODE REVIEW

**Comment by CLAAdmin** [comment]
[CLA assistant check](http://cla.opensmartgridplatform.org:80/OSGP/Documentation?pullRequest=158) <br/>You should sign our Contributor License Agreement in order to get your pull request merged.<br/>

**Comment by rlemmers** [comment]
Opensourcecommunity/Foundation.md and Opensourcecommunity/Communication-and-contact.md also refer to opensource@smartsocietyservices.com. Should those be adapted as well?

**Comment by Sander3003** [comment]
Good point, I will change them as well.

**Comment by Sander3003** [comment]
opensource (at) smartsocietyservices.com is used to request Jira authorization.  Jira is hosted by Smart society services for now so this e-mail adress is fine.

**Comment by Sander3003** [comment]
@rlemmers can you review my changes?

**Pull request merged**
