### PR TITLE
Add device example message

### PR DESCRIPTION
**Pull request by Sander3003**
Community feedback requested an example message for the smartmetering web services. This is the fist example made by @phoutman.

### CODE REVIEW

**Comment by CLAAdmin** [comment]
[CLA assistant check](http://cla.opensmartgridplatform.org:80/OSGP/Documentation?pullRequest=157) <br/>You should sign our Contributor License Agreement in order to get your pull request merged.<br/>

**Comment by rlemmers** [comment]
- Smart metering can be implemented using various protocols. The example is very specific for DSMR. I advise putting the example in the Protocols chapter.
Then link to the example from the webservice operation page or make a general statement "for examples, see section ..." in a centralized location to prevent constantly updating links. 
- Also add a response message example.
- Approving the content should be done by someone from the team in Eindhoven.

**Comment by Sander3003** [comment]
@phoutman can you take a look at this?
https://smartsocietyservices.atlassian.net/browse/OC-362

@rlemmers your name is in the documentation; if this does not reflect the current situation we need to update it.

Current maintainers:

Open smart grid platform and smart lighting domain: Kevin Smeets
Smart metering domain: Bart van der Zwet
Documentation & configuration: Ruud Lemmers

**Comment by rlemmers** [comment]
"@rlemmers your name is in the documentation; if this does not reflect the current situation we need to update it." - when it comes to details about smart metering, someone from that domain should check the content. There's nobody who has expert knowledge about all domains. Therefore, you don't have to modify the maintainer for "Documentation & configuration".

**Comment by rlemmers** [comment]
Any news from @phoutman regarding my input?

**Comment by Sander3003** [comment]
No, not yet, I send @phoutman an e-mail to remind him of this issue. Btw, made some little tweaks to the maintainer section of the documentation to clarify the role of the documentation/configuration maintainer.

**Comment by phoutman** [comment]
I agree with @rlemmers that this is very domain specific and that part should be updated by someone with in-depth knowledge of that domain. But I still think it is the responsibilty of the documentation maintainer to get someone to update the documentation.

**Comment by Sander3003** [comment]
@rlemmers can you file an Jira issue on this topic?

**Comment by Sander3003** [comment]
device configuration example

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.alliander.com/schemas/osgp/common/2014/10" xmlns:ns1="http://www.alliander.com/schemas/osgp/smartmetering/sm-configuration/2014/10">
   <soapenv:Header>
      <ns:ApplicationName>SoapUI</ns:ApplicationName>
      <ns:UserName>testuser</ns:UserName>
      <ns:OrganisationIdentification>test-org</ns:OrganisationIdentification>
   </soapenv:Header>
   <soapenv:Body>
      <ns1:SetConfigurationObjectRequest>
         <ns1:DeviceIdentification>${=testCase.getPropertyValue( "DeviceIdentification" )}</ns1:DeviceIdentification>
         <ns1:SetConfigurationObjectRequestData>
            <ns1:ConfigurationObject>
               <ns1:GprsOperationMode>ALWAYS_ON</ns1:GprsOperationMode>
               <ns1:ConfigurationFlags>
                  <ns1:ConfigurationFlag>
                     <ns1:ConfigurationFlagType>DISCOVER_ON_POWER_ON</ns1:ConfigurationFlagType>
                     <ns1:Enabled>1</ns1:Enabled>
                  </ns1:ConfigurationFlag>
               </ns1:ConfigurationFlags>
            </ns1:ConfigurationObject>
         </ns1:SetConfigurationObjectRequestData>
      </ns1:SetConfigurationObjectRequest>
   </soapenv:Body>
</soapenv:Envelope>

**Pull request merged**
