### PR TITLE
Sander3003 doc improvements

### PR DESCRIPTION
**Pull request by Sander3003**
I tried to address #25 #49 #79

### CODE REVIEW

**Comment by CLAAdmin** [comment]
[CLA assistant check](http://52.16.237.165:80/OSGP/Documentation?pullRequest=80) <br/>All committers of the pull request should sign our Contributor License Agreement in order to get your pull request merged.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Sander3003<br/>:x: web-flow

**Comment by Sander3003** [comment]
I'm not able to check my pull-request on errors, the index does not render in my browser. http://54.77.62.182/job/OSGP_Documentation_pr/lastSuccessfulBuild/artifact/_book/index.html

**Comment by Sander3003** [comment]
@kevinsmeets does it render well in your browser?

**Comment by kevinsmeets** [comment]
Yes, it works fine for me. If you have any problems, use ctrl+f5 or clear your browser's cache.

**Comment by Sander3003** [comment]
It's ready for review

**Pull request merged**
